version: '3.7'
services:
  api:
    build: .
    container_name: atisbalo-api
    # command: sh -c "npx sequelize db:migrate && npm run dev"
    ports:
      - 3000:3000
    environment:
      - ORIGIN=*
      - NODE_ENV=docker
      - DATABASE_HOST=mysql
      - DATABASE_NAME=atisbalo
      - DATABASE_USERNAME=admin
      - DATABASE_PASSWORD=admin
      - DATABASE_DIALECT=mysql
      - PORT=3000
      - REDIS_URL=redis
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    links:
      - mysql
      - redis
    depends_on:
      - mysql
      - redis
  mysql:
    image: mysql:5.7
    container_name: atisbalo-db
    environment:
      MYSQL_DATABASE: 'atisbalo'
      MYSQL_USER: 'admin'
      MYSQL_PASSWORD: 'admin'
      MYSQL_ROOT_PASSWORD: 'admin'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - data:/var/lib/mysql
  redis:
    image: 'redis:4-alpine'
#    restart: 'always'
    command: redis-server
    ports:
      - '6379:6379'

volumes:
  data:
  redisdata:
