branch-defaults:
  master:
    environment: atisbalo-api-dev
environment-defaults:
  atisbalo-api-dev:
    branch: null
    repository: null
global:
  application_name: Atisbalo-Api
  default_ec2_keyname: erp_aws
  default_platform: Docker running on 64bit Amazon Linux
  default_region: eu-west-3
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  sc: git
  workspace_type: Application
