# This is a basic workflow to help you get started with Actions

name: CI Api

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  test:
    runs-on: [self-hosted, staging]
    steps:
    - uses: actions/checkout@v2
    - name: Npm install
      run: npm i
    - name: Jest
      run: npm run test
  build:
    runs-on: [self-hosted, staging]
    needs: test
    steps:
    - uses: actions/checkout@v2
    - name: Npm install
      run: sudo npm installs --production
    - name: Stop Service
      run: sudo systemctl stop atblapi
    - name: Clean folder
      run: rm -r /home/staging/atisbalo/api/*
    - name: Copy files 
      run: cp -R ./ /home/staging/atisbalo/api/
    - name: Start Service
      run: sudo systemctl start atblapi
