# This is a basic workflow to help you get started with Actions

name: CI Api

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  test:
    runs-on: [self-hosted, staging]
    steps:
    - uses: actions/checkout@v2
    - name: Npm install
      run: npm i
    - name: Stop Service
    - uses: mattallty/jest-github-action@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        test-command: "npm run test" 
  build:
    runs-on: [self-hosted, staging]
    steps:
    - uses: actions/checkout@v2
    - name: Npm install
      run: npm install --production
    - name: Stop Service
      run: sudo systemctl start atblapi
    - name: Copy files 
      run: cp -R . /home/staging/atisbalo/api/
    - name: Start Service
      run: sudo systemctl start atblapi
